[package]
name = "affinegeo"
version = "0.1.0"
authors = ["Norbert Fr√∂hlich <norbert.froehlich@alice.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3"
linalg = { path = "../linalg" }

